using OilTrading.Core.Common;
using OilTrading.Core.ValueObjects;

namespace OilTrading.Core.Entities;

public class RiskReport : BaseEntity
{
    public string ReportType { get; set; } = string.Empty; // Daily, Weekly, Monthly, AdHoc
    public string ReportName { get; set; } = string.Empty;
    public DateTime ReportDate { get; set; }
    public DateTime GeneratedAt { get; set; }
    public string GeneratedBy { get; set; } = string.Empty;
    public RiskReportStatus Status { get; set; }
    public string? FilePath { get; set; }
    public int FileSizeBytes { get; set; }
    public string ContentType { get; set; } = "application/json";
    
    // Risk Metrics Summary
    public decimal PortfolioVaR95 { get; set; }
    public decimal PortfolioVaR99 { get; set; }
    public decimal TotalExposure { get; set; }
    public int ActivePositions { get; set; }
    public int OpenLimitBreaches { get; set; }
    public decimal LargestSingleExposure { get; set; }
    
    // Auto-distribution settings
    public string? EmailRecipients { get; set; }
    public bool IsAutoGenerated { get; set; }
    public string? NextScheduledDate { get; set; }
    
    // Navigation properties
    public ICollection<RiskReportSection> Sections { get; set; } = new List<RiskReportSection>();
}

public class RiskReportSection : BaseEntity
{
    public int RiskReportId { get; set; }
    public RiskReport RiskReport { get; set; } = null!;
    public string SectionName { get; set; } = string.Empty;
    public string SectionType { get; set; } = string.Empty; // Summary, Details, Charts, Tables
    public int SortOrder { get; set; }
    public string ContentJson { get; set; } = "{}";
    public string? ChartData { get; set; }
}

public enum RiskReportStatus
{
    Generating = 1,
    Completed = 2,
    Failed = 3,
    Distributed = 4
}