// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OilTrading.Infrastructure.Data;

#nullable disable

namespace OilTrading.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251104120004_AddPaymentDateFieldsToContractsAndSettlements")]
    partial class AddPaymentDateFieldsToContractsAndSettlements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            // This is a simplified builder snapshot - the full model is maintained in ApplicationDbContextModelSnapshot
            // The actual schema changes are defined in the Up/Down methods of the migration class
#pragma warning restore 612, 618
        }
    }
}
