// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OilTrading.Infrastructure.Data;

#nullable disable

namespace OilTrading.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251106_AddPaymentRiskAlerts")]
    partial class AddPaymentRiskAlerts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            // Note: This is a minimal Designer file for the PaymentRiskAlerts migration
            // The full model is in the ApplicationDbContextModelSnapshot.cs file
#pragma warning restore 612, 618
        }
    }
}
