import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export interface User {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: string;
  companyName: string;
  permissions: string[];
  avatar?: string;
  lastLoginAt: Date;
  isActive: boolean;
}

export interface AuthState {
  user: User | null;
  isAuthenticated: boolean;
  isLoading: boolean;
  token: string | null;
}

export interface AuthContextType extends AuthState {
  login: (email: string, password: string, rememberMe?: boolean) => Promise<User>;
  logout: () => void;
  register: (userData: any) => Promise<User>;
  updateUser: (userData: Partial<User>) => Promise<User>;
  hasPermission: (permission: string) => boolean;
  hasRole: (role: string) => boolean;
  isInRole: (roles: string[]) => boolean;
}

const AuthContext = createContext<AuthContextType | null>(null);

export const useAuth = (): AuthContextType => {
  const context = useContext(AuthContext);
  if (!context) {
    throw new Error('useAuth must be used within an AuthProvider');
  }
  return context;
};

interface AuthProviderProps {
  children: ReactNode;
}

// Mock users for demonstration
const MOCK_USERS = [
  {
    id: '1',
    email: 'admin@oiltrading.com',
    password: 'admin123',
    firstName: 'John',
    lastName: 'Admin',
    role: 'Administrator',
    companyName: 'Oil Trading Corp',
    permissions: ['*'], // All permissions
    avatar: '',
    lastLoginAt: new Date(),
    isActive: true,
  },
  {
    id: '2',
    email: 'trader@oiltrading.com',
    password: 'trader123',
    firstName: 'Sarah',
    lastName: 'Johnson',
    role: 'Senior Trader',
    companyName: 'Oil Trading Corp',
    permissions: [
      'contracts.view',
      'contracts.create',
      'contracts.edit',
      'market-data.view',
      'positions.view',
      'risk.view',
    ],
    avatar: '',
    lastLoginAt: new Date(),
    isActive: true,
  },
  {
    id: '3',
    email: 'manager@oiltrading.com',
    password: 'manager123',
    firstName: 'Michael',
    lastName: 'Chen',
    role: 'Risk Manager',
    companyName: 'Oil Trading Corp',
    permissions: [
      'contracts.view',
      'contracts.approve',
      'risk.view',
      'risk.manage',
      'reports.view',
      'users.view',
    ],
    avatar: '',
    lastLoginAt: new Date(),
    isActive: true,
  },
];

const AUTH_STORAGE_KEY = 'oil_trading_auth';
const TOKEN_STORAGE_KEY = 'oil_trading_token';

export const AuthProvider: React.FC<AuthProviderProps> = ({ children }) => {
  const [authState, setAuthState] = useState<AuthState>({
    user: null,
    isAuthenticated: false,
    isLoading: true,
    token: null,
  });

  // Initialize auth state from localStorage on mount
  useEffect(() => {
    const initializeAuth = async () => {
      try {
        const storedToken = localStorage.getItem(TOKEN_STORAGE_KEY);
        const storedUser = localStorage.getItem(AUTH_STORAGE_KEY);

        if (storedToken && storedUser) {
          const user = JSON.parse(storedUser);
          
          // Validate token (in real app, verify with server)
          if (await validateToken(storedToken)) {
            setAuthState({
              user,
              isAuthenticated: true,
              isLoading: false,
              token: storedToken,
            });
          } else {
            // Token invalid, clear storage
            localStorage.removeItem(TOKEN_STORAGE_KEY);
            localStorage.removeItem(AUTH_STORAGE_KEY);
            setAuthState({
              user: null,
              isAuthenticated: false,
              isLoading: false,
              token: null,
            });
          }
        } else {
          setAuthState(prev => ({ ...prev, isLoading: false }));
        }
      } catch (error) {
        console.error('Error initializing auth:', error);
        setAuthState({
          user: null,
          isAuthenticated: false,
          isLoading: false,
          token: null,
        });
      }
    };

    initializeAuth();
  }, []);

  const validateToken = async (token: string): Promise<boolean> => {
    // In a real app, this would make an API call to validate the token
    // For demo purposes, we'll just check if it's not expired
    try {
      const payload = JSON.parse(atob(token.split('.')[1]));
      return payload.exp > Date.now() / 1000;
    } catch {
      return false;
    }
  };

  const generateToken = (user: User): string => {
    // In a real app, this would be generated by the server
    const payload = {
      userId: user.id,
      email: user.email,
      role: user.role,
      exp: Math.floor(Date.now() / 1000) + (24 * 60 * 60), // 24 hours
    };
    
    // This is a mock token - in reality, it would be a proper JWT
    return `mock.${btoa(JSON.stringify(payload))}.signature`;
  };

  const login = async (email: string, password: string, rememberMe = false): Promise<User> => {
    setAuthState(prev => ({ ...prev, isLoading: true }));

    try {
      // Simulate API call delay
      await new Promise(resolve => setTimeout(resolve, 1000));

      // Find user in mock data
      const mockUser = MOCK_USERS.find(u => u.email === email && u.password === password);
      
      if (!mockUser) {
        throw new Error('Invalid email or password');
      }

      if (!mockUser.isActive) {
        throw new Error('Account is deactivated');
      }

      // Create user object (exclude password)
      const user: User = {
        id: mockUser.id,
        email: mockUser.email,
        firstName: mockUser.firstName,
        lastName: mockUser.lastName,
        role: mockUser.role,
        companyName: mockUser.companyName,
        permissions: mockUser.permissions,
        avatar: mockUser.avatar,
        lastLoginAt: new Date(),
        isActive: mockUser.isActive,
      };

      const token = generateToken(user);

      // Store in localStorage if remember me is checked
      if (rememberMe) {
        localStorage.setItem(TOKEN_STORAGE_KEY, token);
        localStorage.setItem(AUTH_STORAGE_KEY, JSON.stringify(user));
      }

      setAuthState({
        user,
        isAuthenticated: true,
        isLoading: false,
        token,
      });

      return user;
    } catch (error) {
      setAuthState(prev => ({ ...prev, isLoading: false }));
      throw error;
    }
  };

  const register = async (userData: any): Promise<User> => {
    setAuthState(prev => ({ ...prev, isLoading: true }));

    try {
      // Simulate API call delay
      await new Promise(resolve => setTimeout(resolve, 1500));

      // Check if email already exists
      const existingUser = MOCK_USERS.find(u => u.email === userData.email);
      if (existingUser) {
        throw new Error('Email address is already registered');
      }

      // Create new user
      const newUser: User = {
        id: `user_${Date.now()}`,
        email: userData.email,
        firstName: userData.firstName,
        lastName: userData.lastName,
        role: userData.role,
        companyName: userData.companyName,
        permissions: ['contracts.view', 'market-data.view', 'positions.view'], // Default permissions
        avatar: '',
        lastLoginAt: new Date(),
        isActive: true,
      };

      const token = generateToken(newUser);

      // Store in localStorage
      localStorage.setItem(TOKEN_STORAGE_KEY, token);
      localStorage.setItem(AUTH_STORAGE_KEY, JSON.stringify(newUser));

      setAuthState({
        user: newUser,
        isAuthenticated: true,
        isLoading: false,
        token,
      });

      return newUser;
    } catch (error) {
      setAuthState(prev => ({ ...prev, isLoading: false }));
      throw error;
    }
  };

  const logout = () => {
    // Clear storage
    localStorage.removeItem(TOKEN_STORAGE_KEY);
    localStorage.removeItem(AUTH_STORAGE_KEY);

    setAuthState({
      user: null,
      isAuthenticated: false,
      isLoading: false,
      token: null,
    });
  };

  const updateUser = async (userData: Partial<User>): Promise<User> => {
    if (!authState.user) {
      throw new Error('No user logged in');
    }

    const updatedUser = { ...authState.user, ...userData };
    
    // Update localStorage
    localStorage.setItem(AUTH_STORAGE_KEY, JSON.stringify(updatedUser));

    setAuthState(prev => ({
      ...prev,
      user: updatedUser,
    }));

    return updatedUser;
  };

  const hasPermission = (permission: string): boolean => {
    if (!authState.user) return false;
    
    // Admin has all permissions
    if (authState.user.permissions.includes('*')) return true;
    
    return authState.user.permissions.includes(permission);
  };

  const hasRole = (role: string): boolean => {
    if (!authState.user) return false;
    return authState.user.role === role;
  };

  const isInRole = (roles: string[]): boolean => {
    if (!authState.user) return false;
    return roles.includes(authState.user.role);
  };

  const contextValue: AuthContextType = {
    ...authState,
    login,
    logout,
    register,
    updateUser,
    hasPermission,
    hasRole,
    isInRole,
  };

  return (
    <AuthContext.Provider value={contextValue}>
      {children}
    </AuthContext.Provider>
  );
};